### PR TITLE
Add WPML support

### PR DESCRIPTION
**Pull request by joldnl**
Adding support for WPML translated pages

### CODE REVIEW

**Comment by cyberscribe** [comment]
Thank you. Has this been very carefully tested for backwards compatibility? It is very important that we don't break anything with new features...

**Comment by joldnl** [comment]
No, this has not been tested for backwards compatibility as this was out of scope for our client project.

**Review by cyberscribe — CHANGES_REQUESTED** [review]
This should not be commented

**Review by cyberscribe — APPROVED** [review]

**Comment by cyberscribe** [comment]
Thanks!

**Pull request merged**
